### ISSUE TITLE
makeTextBold will lost Font size?

### ISSUE THREAD

**Issue by hytaoist** [Rimesh/NotesTextView#1]
I found text lost font size after Bold it. The problem is caused by changeTrait func in makeTextBold.
`

        func changeTrait(trait: UIFontDescriptor.SymbolicTraits) {
        //....
        if let currentFont = initialFont{
            
            var currentTraits = currentFont.fontDescriptor.symbolicTraits
            
            // complement the current traits
            let _ = currentTraits.contains(trait) ? currentTraits.remove(trait) : currentTraits.update(with: trait)
            
            if let changedFontDescriptor = currentFont.fontDescriptor.withSymbolicTraits(currentTraits) {
                let updatedFont = UIFont(descriptor: changedFontDescriptor , size: 0)
                
                if selectedRange.length != 0{
                    textStorage.enumerateAttribute(.font, in: selectedRange, options: .longestEffectiveRangeNotRequired) { (_, range, stop) in
                        textStorage.beginEditing()
                        textStorage.addAttribute(.font, value: updatedFont, range: range)
                        textStorage.endEditing()
                    }
                }
                
                typingAttributes[NSAttributedString.Key.font] = updatedFont
                updateVisualForKeyboard()
            }
        }
      }
`

Then i fix in it 
`
        if let currentFont = initialFont{
            
            var currentTraits = currentFont.fontDescriptor.symbolicTraits
            
            // complement the current traits
            let _ = currentTraits.contains(trait) ? currentTraits.remove(trait) : currentTraits.update(with: trait)
            
            if let changedFontDescriptor = currentFont.fontDescriptor.withSymbolicTraits(currentTraits) {
                // Fix lost font size.
                let currentFontSize = currentFont.pointSize
                let updatedFont = UIFont(descriptor: changedFontDescriptor , size: currentFontSize)
                
                if selectedRange.length != 0{
                    textStorage.enumerateAttribute(.font, in: selectedRange, options: .longestEffectiveRangeNotRequired) { (_, range, stop) in
                        textStorage.beginEditing()
                        textStorage.addAttribute(.font, value: updatedFont, range: range)
                        textStorage.endEditing()
                    }
                }
                
                typingAttributes[NSAttributedString.Key.font] = updatedFont
                updateVisualForKeyboard()
            }
        }
`
could you update it ?

**Comment by Rimesh** [comment]
@hytaoist Can you share a video which shows making any text bold losing its font size?
May be I may have missed an edge case but I am not able to replicate the issue.
I guess font size 0 respects the current font size.

**Comment by Rimesh** [comment]
@hytaoist Thanks for reporting the issue.
I have updated the code based on your suggestion.
